# Numpy

In [2]:
a = [1,2,3,4]
b = [0,2,4,8]

In [3]:
ab = []

In [4]:
for i in range(0, len(a)):
    ab.append(a[i] * b[i])
    
ab

[0, 4, 12, 32]

In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3,4])
b = np.array([0,2,4,8])

In [7]:
a*b

array([ 0,  4, 12, 32])

while array takes four integer storage, numpy takes only one integer for four-elements array

## Creating numpy array

In [8]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [9]:
a = np.array([1,2,3,4,5])

In [10]:
type(a)

numpy.ndarray

In [11]:
np.array([3.14, 4, 2, 13])

array([ 3.14,  4.  ,  2.  , 13.  ])

as seen above, it transformed all the integers to decimal. 
But of course we can control that

In [12]:
np.array([3.14, 2, 4, 8], dtype = "float32")

array([3.14, 2.  , 4.  , 8.  ], dtype=float32)

In [13]:
np.array([3.14, 2, 4, 8], dtype = "int")

array([3, 2, 4, 8])

## Creating numpy array from zero

In [14]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((3,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [17]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

above code means create an array from 0 to 31 with multiples of 3

In [19]:
np.linspace(0,1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [23]:
np.linspace(1,10, 10, dtype="int")

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

linspace means create an array with third parameter's number betweeen first two parameters 

In [24]:
np.random.normal(10, 4, (3,4))  # average=10, standard deviation=4, array dimensions = (3,4)

array([[17.50211246,  9.48173335,  8.02703288,  8.56351603],
       [12.99337595, 15.50335723,  6.31299722, 10.72280993],
       [ 7.67128863, 19.56349157,  9.15053423, 12.56140812]])

In [27]:
np.random.randint(0,10, (3,3))  #from:0, to:10, dimension=(3,3)

array([[8, 0, 8],
       [2, 9, 0],
       [9, 0, 9]])

## Features of Numpy:
* **ndim**: number of dimension
* **shape**: info of dimension
* **size**: total element number
* **dtype**: array data type


In [31]:
np.random.randint(10, size = 10)  # create an array with numbers less than 10 and with size of 10

array([9, 6, 2, 3, 6, 4, 2, 6, 3, 6])

In [32]:
a = np.random.randint(10, size = 10)

In [33]:
a.ndim

1

In [34]:
a.shape

(10,)

In [35]:
a.size

10

In [36]:
a.dtype

dtype('int32')

In [37]:
b = np.random.randint(10, size = (3,5))

In [38]:
b

array([[9, 8, 4, 9, 4],
       [4, 3, 2, 6, 2],
       [8, 0, 8, 3, 4]])

In [39]:
b.ndim

2

In [40]:
b.shape

(3, 5)

In [41]:
b.size

15

In [42]:
b.dtype

dtype('int32')

## Reshaping

In [43]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a = np.arange(1,10)

In [46]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a.ndim

1

In [49]:
b = a.reshape((1,9))

In [50]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
b.ndim

2

as seen above, I reshaped one dim array to two dim array with .reshape()

## Concatenation

In [52]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [53]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [54]:
z = np.array([7,8,9])

In [55]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### two dimension concatenation

In [56]:
a = np.array([[1,2,3],
            [4,5,6]])

In [57]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([a,a], axis=0)  

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [60]:
np.concatenate([a,a], axis=1)  

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Splitting

In [62]:
x = np.array([1,2,3,99,99,3,2,1])

In [63]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [64]:
np.split(x, [3,4])

[array([1, 2, 3]), array([99]), array([99,  3,  2,  1])]

In [65]:
np.split(x, [0,3])

[array([], dtype=int32), array([1, 2, 3]), array([99, 99,  3,  2,  1])]

In [66]:
a,b,c = np.split(x, [3,5])

In [67]:
a

array([1, 2, 3])

In [68]:
b

array([99, 99])

In [69]:
c

array([3, 2, 1])

### two Dimension Splitting

In [70]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
np.vsplit(m, [2])  # split until 2nd index which is -> [8,9,10,11]

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [72]:
np.vsplit(m, [0,2])

[array([], shape=(0, 4), dtype=int32),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [74]:
first, second = np.vsplit(m, [2])

In [75]:
first

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [76]:
second

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

vsplit splits vertically and there is another split methot hsplit which splits horizontally

In [77]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [79]:
left, right = np.hsplit(m, [2])

In [80]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [81]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Sorting

In [82]:
import numpy as np

In [83]:
v = np.array([2,1,4,3,5])

In [84]:
v

array([2, 1, 4, 3, 5])

In [85]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [86]:
v

array([2, 1, 4, 3, 5])

In [87]:
v.sort()

In [88]:
v

array([1, 2, 3, 4, 5])

numpy's sort method did not change original version of array, but .sort() method did

## two dimensional array sorting

In [92]:
m = np.random.normal(20, 5, (3,3))

In [93]:
m

array([[15.61186382, 20.90614682, 18.78218077],
       [20.72618618, 20.18336219, 18.17274873],
       [12.91467867, 19.88707149, 18.16020955]])

In [94]:
np.sort(m, axis=1)

array([[15.61186382, 18.78218077, 20.90614682],
       [18.17274873, 20.18336219, 20.72618618],
       [12.91467867, 18.16020955, 19.88707149]])

In [95]:
np.sort(m, axis=0)

array([[12.91467867, 19.88707149, 18.16020955],
       [15.61186382, 20.18336219, 18.17274873],
       [20.72618618, 20.90614682, 18.78218077]])

when axis=1 it sorts rows, and when axis=0 it sorts columns

## Accessing elements with indexes

In [96]:
import numpy as np
a = np.random.randint(10, size=10)
a

array([4, 8, 1, 6, 8, 5, 7, 9, 3, 6])

In [97]:
a[0]

4

In [98]:
a[-1]

6

In [99]:
a[-2]

3

In [100]:
a[0] = 100

In [101]:
a

array([100,   8,   1,   6,   8,   5,   7,   9,   3,   6])

In [105]:
m = np.random.randint(10, size = (3,5))
m

array([[8, 0, 6, 9, 5],
       [4, 5, 9, 1, 1],
       [7, 2, 2, 4, 0]])

In [106]:
m[0,0]

8

In [107]:
m[1,1]

5

In [108]:
m[1, -1]

1

In [109]:
m[1,4]

1

In [110]:
m[1, -1] = 99

In [111]:
m

array([[ 8,  0,  6,  9,  5],
       [ 4,  5,  9,  1, 99],
       [ 7,  2,  2,  4,  0]])

In [114]:
m[1, -1] = 55.5  # this operation will not change the type of whole array so it will stay as integer matrix

In [115]:
m

array([[ 8,  0,  6,  9,  5],
       [ 4,  5,  9,  1, 55],
       [ 7,  2,  2,  4,  0]])

## Slicing

In [116]:
import numpy as np

In [117]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [118]:
a[0:3]

array([20, 21, 22])

In [119]:
a[:3]

array([20, 21, 22])

In [120]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [123]:
a[0::2]  # that means start from 0st index and go 2step 

array([20, 22, 24, 26, 28])

In [124]:
a[2::2]

array([22, 24, 26, 28])

In [125]:
a[0::3]

array([20, 23, 26, 29])

### two dimensional slicing 

In [126]:
m = np.random.randint(10, size = (5,5))

In [127]:
m

array([[9, 9, 3, 7, 4],
       [8, 7, 5, 9, 0],
       [0, 6, 7, 8, 7],
       [7, 9, 3, 6, 5],
       [6, 0, 8, 4, 8]])

In [133]:
m[:,0]  ## : means all rows

array([9, 8, 0, 7, 6])

In [134]:
m[:,1]

array([9, 7, 6, 9, 0])

In [135]:
m[:,-1]

array([4, 0, 7, 5, 8])

In [137]:
m

array([[9, 9, 3, 7, 4],
       [8, 7, 5, 9, 0],
       [0, 6, 7, 8, 7],
       [7, 9, 3, 6, 5],
       [6, 0, 8, 4, 8]])

In [138]:
m[0,:]  # : means all columns

array([9, 9, 3, 7, 4])

In [139]:
m[0]

array([9, 9, 3, 7, 4])

In [141]:
m[0:2, 0:3]  # first one is rows and second is columns

array([[9, 9, 3],
       [8, 7, 5]])

In [143]:
m[::, :2]  # all rows and from 0 to 2 columns

array([[9, 9],
       [8, 7],
       [0, 6],
       [7, 9],
       [6, 0]])

In [144]:
m[:, 0:2]

array([[9, 9],
       [8, 7],
       [0, 6],
       [7, 9],
       [6, 0]])

In [145]:
m

array([[9, 9, 3, 7, 4],
       [8, 7, 5, 9, 0],
       [0, 6, 7, 8, 7],
       [7, 9, 3, 6, 5],
       [6, 0, 8, 4, 8]])

In [146]:
m[1:3, 0:2]

array([[8, 7],
       [0, 6]])

## Operations after slicing

In [147]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[4, 5, 0, 5, 7],
       [8, 4, 4, 9, 6],
       [7, 5, 5, 4, 2],
       [2, 2, 6, 1, 6],
       [0, 4, 3, 5, 0]])

In [148]:
sub_a = a[0:3, :2]
sub_a

array([[4, 5],
       [8, 4],
       [7, 5]])

In [149]:
sub_a[0,0] = 999
sub_a[1,1] = 888

In [150]:
sub_a

array([[999,   5],
       [  8, 888],
       [  7,   5]])

In [151]:
a

array([[999,   5,   0,   5,   7],
       [  8, 888,   4,   9,   6],
       [  7,   5,   5,   4,   2],
       [  2,   2,   6,   1,   6],
       [  0,   4,   3,   5,   0]])

as seen above, operations made in subarray but also affected original array

In [152]:
m = np.random.randint(10, size = (5,5))
m

array([[7, 3, 6, 3, 7],
       [5, 0, 8, 4, 9],
       [9, 2, 0, 1, 1],
       [9, 1, 2, 0, 6],
       [6, 6, 4, 8, 2]])

In [154]:
sub_b = m[:3, :2].copy()  # with this copy() method, we take another array from original
sub_b

array([[7, 3],
       [5, 0],
       [9, 2]])

In [155]:
sub_b[0,0] = 999

In [156]:
sub_b

array([[999,   3],
       [  5,   0],
       [  9,   2]])

In [157]:
m

array([[7, 3, 6, 3, 7],
       [5, 0, 8, 4, 9],
       [9, 2, 0, 1, 1],
       [9, 1, 2, 0, 6],
       [6, 6, 4, 8, 2]])

as seen above, with copy(), there is no change in original array

## Accesing elements with Fancy Index 

In [160]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [161]:
v[1]

3

In [162]:
v[3]

9

In [163]:
v[5]

15

In [164]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [165]:
go_get = [1,3,5]

In [166]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [167]:
v[go_get]

array([ 3,  9, 15])

### fancy index in two dimension

In [168]:
m = np.arange(9).reshape((3,3))

In [169]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [170]:
row = np.array([0,1])
column = np.array([1,2])

In [171]:
m[row, column]

array([1, 5])

In [175]:
# basic index and fancy index

In [176]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [177]:
m[0, [1,2]]

array([1, 2])

In [178]:
# slice and fancy index
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Conditional Element Operations

In [179]:
import numpy as np
v = np.array([1,2,3,4,5])

In [180]:
v > 5

array([False, False, False, False, False])

In [181]:
v < 3

array([ True,  True, False, False, False])

In [182]:
v[v<3]

array([1, 2])

In [183]:
v[v>3]

array([4, 5])

In [184]:
v[v>=3]

array([3, 4, 5])

In [185]:
v[v!=3]

array([1, 2, 4, 5])

In [186]:
v * 2

array([ 2,  4,  6,  8, 10])

In [187]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [188]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

## Mathematical Operations

In [189]:
import numpy as np
v = np.array([1,2,3,4,5])

In [190]:
v - 1

array([0, 1, 2, 3, 4])

In [191]:
v * 5

array([ 5, 10, 15, 20, 25])

In [192]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [193]:
v*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [198]:
# ufunc

In [199]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [200]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [201]:
np.multiply(v, 4)

array([ 4,  8, 12, 16, 20])

In [202]:
np.divide(v, 2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [203]:
np.power(v,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [204]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [205]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [206]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [207]:
np.absolute(np.array([-3,-2,-1,0,1,2,3]))

array([3, 2, 1, 0, 1, 2, 3])

In [208]:
np.sin(360)

0.9589157234143065

In [209]:
np.cos(180)

-0.5984600690578581

In [213]:
np.sin(90)

0.8939966636005579

In [214]:
v = np.array([1,2,3])

In [215]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [216]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [223]:
np.log2(np.array([1,4,27,64]))

array([0.       , 2.       , 4.7548875, 6.       ])

In [227]:
# we can write this to see summary numpy documentation
?np

## Statistical Calculations Numpy

* np.mean(arr,axis=0) | Returns mean along specific axis
* arr.sum() | Returns sum of arr
* arr.min() | Returns minimum value of arr
* arr.max(axis=0) | Returns maximum value of specific axis
* np.var(arr) | Returns the variance of array
* np.std(arr,axis=1) | Returns the standard deviation of specific axis
* arr.corrcoef() | Returns correlation coefficient of array

In [231]:
v

array([1, 2, 3])

In [232]:
np.mean(v)

2.0

In [233]:
v.sum()

6

In [234]:
v.min()

1

In [235]:
np.var(v)

0.6666666666666666

In [237]:
np.std(v)

0.816496580927726

## Two Unknowns Equation Solving with Numpy

In [239]:
import numpy as np

5*x0 + x1 = 12


x0 + 3*x1 = 10

In [242]:
a = np.array([[5,1], [1,3]])  # they are coefficient of x0 and x1
b = np.array([12, 10])

In [243]:
a

array([[5, 1],
       [1, 3]])

In [244]:
b

array([12, 10])

In [245]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])